= SCLI Tutorial

This document describes the features of the SCLI library in form of usage
examples, starting from easy ones and advancing to more complex scenarios.
Most of the examples do not build upon each other; so you might directly
proceed to the section you are interested in the most.

NOTE: While not strictly necessary, it is helpful to understand the underlying
concepts used by SCLI before browsing the usage examples in this document. They
are described in the link:README.adoc[README document].

== Introduction

This document describes the usage of the SCLI library based on an imaginary
command line interface application called _transfer_. _transfer_ can download
or upload a number of files from or to a server. It supports a number of
options to configure the data transfer; for instance, it is possible to encrypt
data, to set timeouts, or to enable a _dry-run_ mode. For the server, which is
the target of the transfer operation, the application supports multiple
transfer protocols; depending on the protocol selected, different additional
parameters are expected. So if the target server uses the HTTP protocol, the
user needs to provide credentials for _basic auth_ authentication.

The general command line for our hypothetical _transfer_ application looks as
follows:

`transfer [options] <command> <file1> [<file2>..<fileN>] <serverUri>`

_<command>_ can be either `upload` or `download` and determines the direction
of the data transfer. After the command, an arbitrary number of file paths to
be transferred are listed; but there must be at least one file. The last
argument is the URI of the server, which is the target of the transfer. The
_spec_ of this URI is evaluated to determine the server type. The server type
influences the set of parameters accepted by the application; options
configuring an HTTP server are only accepted if the server type is actually
HTTP.

== Sample code

Most of the code examples used throughout this document are taken from the
link:./src/test/scala/com/github/scli/sample/transfer/TransferParameterManager.scala[TransferParameterManager]
module. It defines the data structures to represent the arguments accepted by
the _transfer_ application and declares extractors to actually process the
arguments. For your own applications, you can follow a similar pattern to keep
the logic of command line processing in a dedicated parameter manager class.

When you inspect the _TransferParameterManager_ source code, you will see a
number of case classes ending on the suffix _Config_ that are representations
of the command line arguments accepted by the sample application. The top-level
case class is _TransferCommandConfig_; a successful processing of the command
line yields an instance of this class. With such an object available, the
application has direct and type-safe access to the arguments provided by the
user. The examples in this document show how the single arguments are read from
the command line, processed, and eventually stored in those config objects.

There is also a test class for the _TransferParameterManager_ module, using the
_transfer_ sample application to test the library against a realistic use case:
link:./src/test/scala/com/github/scli/sample/transfer/TransferParameterManagerSpec.scala[TransferParameterManagerSpec].
Use this class as a source for ideas how to test your own command line
processing logic based on the SCLI library.

== Usage examples

This section contains many code examples showing SCLI in action to process the
command line of the _transfer_ sample application.

=== Basic extractors

In order to read the values of arguments from the command line and convert them
to a suitable representation, the developer has to define extractors. This
subsection demonstrates the domain specific language offered by SCLI for the
definition of basic extractors.

The functions used within this section are defined by the _ParameterExtractor_
module. So they require this import:

`import com.github.scli.ParameterExtractor._`

NOTE: The DSL provided by SCLI is implemented using Scala _implicit functions_,
which are also defined by the `ParameterExtractor` class; the wildcard import
above makes sure that these functions are available in the current scope.

==== Extracting a single string option value

One entry point into extracting the values of options is the _optionValue()_
function. It returns a _CliExtractor_ of type _SingleOptionValue[String]_. This
can be the basis for further data type conversions. The function expects the
key of the option as argument. It assumes that the option can have at most
one value (which is reflected by the result type). This should be the most
typical use case.

One example of such an option in the sample application is the `tag` option.
It allows the user to specify a label to be assigned to the transfer operation.
The assignment only happens if the option is present:

 transfer --tag "v1.1.2" upload ./source /target

This use case is actually handled by the most basic extractor:

[source,scala]
----
val extTag = optionValue("tag")
----

This extractor yields an `Option[String]`, which corresponds to the basic
`SingleOptionValue[String]` type; it fails if the option occurs multiple times
and thus has more than one value.

NOTE: Actually, `SingleOptionValue[String]` corresponds to a
`Try[Option[String]]`. Extractors typically return `Try` types because
transformations on the user input can always fail. When combining the results
of extractors failed extractions are detected and collected into a meaningful
error message.

==== Extracting an option with multiple string values

The _transfer_ sample application supports the command line option `log` to
define lines for the transfer log. The option can occur multiple times to
generate multiple log entries, as in the following fragment:

 transfer --log "Updating sources" --log "Version 1.1.2-2020-06-28" \
    --log "by test.user@scli.org" upload ./source /target

The type of the `log` option is `Iterable[String]`, which corresponds to the
basic `OptionValue[String]` type. For the creation of extractors of this type,
the _multiOptionValue()_ function is responsible. Its signature is analogous to
the one of the _optionValue()_ function:

[source,scala]
----
val extLog = multiOptionValue("log")
----

Except for the different result type, extractors created by the functions
_optionValue()_ and _multiOptionValue()_ are very similar in the features they
support; a common set of transformations is available for both. We will discuss
such transformations later in this tutorial.

==== Extracting an option with a mandatory string value

Some parameters must always be present for the application to fulfill its
function. In the _transfer_ application, if the target is an HTTP server, the
user must provide the credentials for basic auth - a user name, and a password.

To indicate that an extractor yields a single, mandatory value, it needs to be
decorated with the `mandatory` modifier. This is actually a difference between
extractors for single option values (constructed via `optionValue()`) and those
for multi option values (created by `multiOptionValue()`): `mandatory` only
works for single values. The modifier changes the result type of the extractor
from `Try[Option[String]]` to `Try[String]`. The extractor produces a failure
if no value is present for this argument. The following snippet shows the
declaration of the extractor for the user name for the HTTP server:

[source,scala]
----
val extUsr = optionValue("user")
  .mandatory
----

=== Input parameters

Input values are elements on the command line that cannot be assigned to
options. The _transfer_ sample application uses the following parameters of
this type (in this order) - refer to the <<Introduction>> section for further
details:

* A command that determines the direction of the transfer
* A sequence of paths to be transferred
* The URI of the target server

This set of input parameters demonstrates a number of use cases:

* Input parameters typically get their meaning from their position on the
  command line. The application specifies that the first parameter is the
  transfer command, while the last is the server URI. Note that other options
  can appear between input parameter values; they are ignored when extracting
  the values of a specific input parameter.
* Like options, input parameters can have either a single or multiple values.
  Input parameters with multiple values make the positioning more complicate:
  If the exact number of values for a parameter is not known (as is the case in
  the sample application for the number of paths to transfer), specifying
  absolute parameter indices is no longer possible.
* Despite from their special syntax, the values of input parameters should be
  accessible in the same way as option values; for instance, transformations
  on values should be possible.

We will demonstrate how SCLI addresses these use cases.

==== Extracting an input parameter with a single value at a specific position

For the creation of extractors for input parameters, the SCLI library offers a
pair of functions analogously to `optionValue()`, and `multiOptionValue()`:
`inputValue()` produces an extractor for an input parameter with a single
value; extractors generated by `inputValues()` in contrast support multiple
values.

In the _transfer_ sample application, the easiest input parameter is the first
one, the transfer command. Its position on the command line is known exactly.
The `inputValue()` function expects this position as the only mandatory
parameter. Parameter indices are 0-based; so the following code fragment
produces an extractor for this input parameter:

[source,scala]
----
val extCommand: CliExtractor[SingleOptionValue[String]] = inputValue(0)
----

Input parameters do not necessarily need a key like options; it is, however,
recommended defining one, as these keys appear in error or usage messages. If
the developer does not define a key, SCLI generates a synthetic key based on
the parameter index. To define a key explicitly, pass the _optKey_ parameter
to the function (it is an `Option`, which is `None` per default):

[source,scala]
----
val extCommand = inputValue(optKey = Some("transferCommand"), index = 0)
----

==== Extracting an input parameter with multiple values

To deal with input parameters with multiple values, there is the
`inputValues()` function. In contrast to `inputValue()`, it does not take a
single parameter index, but a pair of _fromIndex_ and _toIndex_. Like the
index parameter for `inputValue()`, these indices start with 0. Both are
inclusive. So if you want to assign the first three input values to a
parameter, you have to set the _fromIndex_ to 0 and the _toIndex_ to 2.

For the files to transfer in the sample application, we have the problem that
the exact number of parameter values is unknown; the user can provide an
arbitrary number of paths. So how to set the _toIndex_ parameter?

To deal with such use cases, there is the possibility to specify negative index
values. A negative index is interpreted from the end of the command line: The
index value -1 references the last input parameter; the index -2 the second
last, etc.

In the _transfer_ application, the list of files to transfer starts from the
second input value (after the transfer command) and goes to the one before the
last; the last one is the URI of the server. So the indices to specify are
_fromIndex_ = 1 and _toIndex_ = -2. Here is the code fragment that constructs
the extractor for the _transferFiles_ parameter:

[source,scala]
----
val extSrcFiles: CliExtractor[OptionValue[String]] =
  inputValues(fromIdx = 1, toIdx = -2, optKey = Some("transferFiles"))
----

Now for the last remaining input parameter, the server URI, we can use the same
trick. As it is the last parameter, we simply set the index to -1, resulting
in:

[source,scala]
----
val extServerUri = inputValue(optKey = Some("serverUri"), index = -1)
  .mandatory
----

==== Defining the multiplicity of parameters

There is still a problem with the definition of the input parameter for the
files to transfer: The current declaration states that the parameter values are
in the range from the second to the second last parameter value. This could
yield an empty list of values if the command line contains only the transfer
command and the server URI. The application logic, however, requires at least
one file to be present.

Single-valued parameters support the `mandatory` modifier to declare that a
value is required. For parameters with multiple values, there is a means
allowing even more control over the exact number of values supported: the
`multiplicity` modifier. The modifier takes up to two parameters for the
minimum and maximum number of parameter values. If a bound is unspecified, this
means that there is no restriction in this direction. The default multiplicity
assumed for a multi-valued parameter is `0..\*` - an arbitrary number of values
is allowed. For the _transferFiles_ parameter we have to change this to
`1..*`, so that at lest one value must be provided. To do this, we extend the
declaration of the parameter as in the following fragment:

[source,scala]
----
val extSrcFiles = inputValues(fromIdx = 1, toIdx = -2, optKey = Some("transferFiles"))
  .multiplicity(atLeast = 1)
----

Now the extractor generates a failure if no file to transfer has been passed
in.

NOTE: The `multiplicity` modifier has been introduced in the context of
input parameters; but it is supported by all kinds of parameters with multiple
values.
